


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ALWAYS
    include-exception: false


